# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "avnav-mapproxy-plugin"
arch: "all"
platform: "linux"
version: "20210201"
keep_version: true
section: "default"
priority: "extra"
depends:
- avnav
- python3-mapproxy
maintainer: "Andreas Vogel <andreas@wellenvogel.de>"
description: |
  AvNav plugin to handle online charts with mapproxy
homepage: "https://example.com"
license: "MIT"
#scripts:
#  postinstall: install/postinstall
contents:
- src: ./*.py
  dst: /usr/lib/avnav/plugins/mapproxy/
- src: ./plugin.js
  dst: /usr/lib/avnav/plugins/mapproxy/plugin.js  
- src: ./plugin.css
  dst: /usr/lib/avnav/plugins/mapproxy/plugin.css
- src: ./*.png
  dst: /usr/lib/avnav/plugins/mapproxy/
- src: ./gui/build/release/*
  dst: /usr/lib/avnav/plugins/mapproxy/gui
#- src: ./gui/icons/*
#  dst: /usr/lib/avnav/plugins/mapproxy/gui/icons
- src: ./gui/build/release/lib/*
  dst: /usr/lib/avnav/plugins/mapproxy/gui/lib
- src: ./boxes/*
  dst: /usr/lib/avnav/plugins/mapproxy/boxes
- src: ./avnav_*.yaml
  dst: /usr/lib/avnav/plugins/mapproxy/